"""Initial database migration

Revision ID: 52a2c3915631
Revises: 
Create Date: 2021-01-20 04:57:04.441886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a2c3915631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postal_codes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postal_codes_postal_code'), 'postal_codes', ['postal_code'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('external_number', sa.String(), nullable=True),
    sa.Column('internal_number', sa.String(), nullable=True),
    sa.Column('postal_code_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['postal_code_id'], ['postal_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_email'), 'stores', ['email'], unique=True)
    op.create_index(op.f('ix_stores_postal_code_id'), 'stores', ['postal_code_id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_product_id'), 'stocks', ['product_id'], unique=False)
    op.create_index(op.f('ix_stocks_sku'), 'stocks', ['sku'], unique=True)
    op.create_index(op.f('ix_stocks_store_id'), 'stocks', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_store_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sku'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_product_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_stores_postal_code_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_email'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('products')
    op.drop_index(op.f('ix_postal_codes_postal_code'), table_name='postal_codes')
    op.drop_table('postal_codes')
    # ### end Alembic commands ###
